name: Global Information

on: workflow_dispatch

jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Print all information
        run: |
          echo "${{ github }}"
          echo "${{ toJSON(github) }}"
